### ISSUE TITLE
MainMenuScreen/Buttons + Background (Event handeling #1)

### ISSUE THREAD

**Issue by cuvidk** [bogdanguranda/sokobug#13]
*Set the background image
*Set the position of the buttons
*Handle how the buttons will behave (LOOK) when they're in one of the following states :
>normal state (not touched, not pressed, mouse is not over them)
>mouse over them state - to be discussed (desktop / android behavior)
>selected state (pressed - enter / click / touch)

**Comment by cuvidk** [comment]
only valid background image left

**Comment by bogdanguranda** [comment]
I'm going to close this issue and make another one just for the artist(for valid background image) so we know clearer what has been done and what's needed to be done.
