### ISSUE TITLE
IntroScreen/FinalLogos(Graphics)

### ISSUE THREAD

**Issue by bogdanguranda** [bogdanguranda/sokobug#17]
Final logos from the artist.

**Comment by andreiguranda** [comment]
Aveti cele 2 logouri. Astept sa imi confirmati daca sunt ok, sau daca mai vreti modificari :)

**Comment by bogdanguranda** [comment]
Super 😉

**Comment by bogdanguranda** [comment]
Putem as inchidem issue.
