### ISSUE TITLE
ChooseLevel/Buttons(Graphic)

### ISSUE THREAD

**Issue by bogdanguranda** [bogdanguranda/sokobug#30]
- an back to menu button(that will be used also in OptionsScreen and CreditsScreen and anywhere else it will be needed)
- the level button(with the states: NORMAL, SELECTED(mouse over or keyboard selection), ACTIVATED(enter or click). This will be used for all levels, the numbers will be added from the code with some font.

**Comment by andreiguranda** [comment]
se poate folosi butonul generic pentru moment

**Comment by bogdanguranda** [comment]
Ok.

**Comment by bogdanguranda** [comment]
Created new issue for the remaining of this issue(level buttons) and added the idea of a dead button for not opened yet levels.
