### ISSUE TITLE
MainMenuScreen/FinalBackgroundImage(Graphic)

### ISSUE THREAD

**Issue by bogdanguranda** [bogdanguranda/sokobug#40]
Final background image for the main menu.

**Comment by bogdanguranda** [comment]
This background will be also used in Options, ChooseLevel and maybe Credits Screen(CreditsScreen may look better just having a blank background).

**Comment by cuvidk** [comment]
ouk

**Comment by bogdanguranda** [comment]
:smiley_cat:

**Comment by bogdanguranda** [comment]
Done.
